USE PhotoShowdownDB;
GO

ALTER TABLE Matches
ALTER COLUMN StartDate DATETIME;

ALTER TABLE Matches
ALTER COLUMN EndDate DATETIME;

ALTER TABLE Rounds
ALTER COLUMN StartDate DATETIME;

ALTER TABLE Rounds
ALTER COLUMN EndDate DATETIME;