version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "donfil123!!!"
      ACCEPT_EULA: "Y"
  api:
    build: ./PhotoShowdownBackend
    ports:
      - "5299:5299"
      - "8080:8080"
      - "7222:7222"
    depends_on:
      - db
    environment:
      CONNECTION_STRING: "Server=db;Database=PhotoShowdownDB;User Id=sa;Password=donfil123!!!;trusted_connection=false;MultipleActiveResultSets=true;TrustServerCertificate=true;"
  frontend:
    build: ./photo-showdown-frontend
    ports:
      - "4200:4200"
      - "80:80"
    depends_on:
      - api