name: Angular Unit Tests

on:
  pull_request:
    branches: [ dev, rc, prod ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Working Directory
        run: cd photo-showdown-frontend

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run format

      - name: Run Build
        run: npm run build --if-present

      - name: Run Unit Tests
        run: npm run test:ci